version: '3.8'
services:
  db:
    image: postgis/postgis:13-3.1
    container_name: cycle-parking-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cycle_parking
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
